
Book.create!(name: "The Ruby on Rails Tutorial", author: "Michale Hartl", description: "The Ruby on Rails Tutorial book and screencast series teach you how to develop and deploy real, industrial-strength web applications with Ruby on Rails, the open-source web framework that powers top websites such as Twitter, Hulu, GitHub, and the Yellow Pages", slug: "0596003307")
Book.create!(name: "Everyday Rails Testing with Rspec", author: "Aaron Summer", description: "Real-world advice for adding reliable tests to your Rails apps with RSpec, complete with expanded, exclusive content and a full sample application", slug: "0321127420")
Book.create!(name: "The Well-Grounded Rubyist", author: "David A. Black", description: "The Well-Grounded Rubyist takes you from interested novice to proficient practitioner.", slug: "978-1934356555")
Book.create!(name: "The Pragmatic Programme", author: "Andrew Hunt", description: "Straight from the programming trenches, The Pragmatic Programmer: From Journeyman to Master cuts through the increasing specialization and technicalities of modern software development to examine the core process—what do you do, as an individual and as a team, if you want to create software that’s easy to work with and good for your users.", slug: "9780201616224")
Book.create!(name: "Agile Web Development with Rails 4", author: "Sam Ruby", description: "Rails just keeps on changing. Both Rails 3 and 4, as well as Ruby 1.9 and 2.0, bring hundreds of improvements, including new APIs and substantial performance enhancements. The fourth edition of this award-winning classic has been reorganized and refocused so it’s more useful than ever before for developers new to Ruby and Rails.", slug: "9781937785567")

User.create!(name: "Mayra Cabrera", email: "mayra@hackerschool.com", password: "password", password_confirmation: "password")
User.create!(name: "Cosme Fulanito", email: "cosme@hackerschool.com", password: "password", password_confirmation: "password")
